### ISSUE TITLE
Running the Blockchain locally

### ISSUE THREAD

**Issue by newnewb** [SaifRehman/tendermint-chat-app#16]
Tried running the app, ran both app.js and the ionic server after setting the baseURL to http://localhost:46657

Got those two errors in the frontend when posting and trying to fetch messages?

![tendermint](https://user-images.githubusercontent.com/19394906/38055814-d51639aa-32eb-11e8-84b4-816a091181a1.PNG)

What's the right way to setup the frontend to use a local server?

**Comment by SaifRehman** [comment]
sorry i have to update the readme, there are lots of thing updated in the repo

**Comment by SaifRehman** [comment]
all express rest api are removed

**Comment by SaifRehman** [comment]
updated and fixed!
