### ISSUE TITLE
CORS Issue?

### ISSUE THREAD

**Issue by faddat** [SaifRehman/tendermint-chat-app#3]
<img width="543" alt="screen shot 2018-02-28 at 10 46 30 am" src="https://user-images.githubusercontent.com/7142025/36769115-da785ac8-1c74-11e8-81a7-887d4a8b7f04.png">

The solution is probably really simple, I'm just not certain what it is.

**Comment by SaifRehman** [comment]
Hello @faddat Thanks for pointing this out. Yes the solution is simple, we need to install Allow-Control-Allow-Origin: * chrome plugin. I will update that in readme.
link: https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi?hl=en

**Comment by SaifRehman** [comment]
@faddat  updated!

**Comment by faddat** [comment]
Awesome, thank you!
