### ISSUE TITLE
IBM Cloud Support

### ISSUE THREAD

**Issue by SaifRehman** [SaifRehman/tendermint-chat-app#5]

**Comment by faddat** [comment]
What's needed for IBM cloud support in this case?

**Comment by SaifRehman** [comment]
hello @faddat I have aready created docker image for the app, all the port seems to work but only lotion port is not been able to be accessed. can you look at it please

**Comment by SaifRehman** [comment]
I want to run tendermint app on IBM cloud using containers @faddat  for that I have already created dockerfile
https://github.com/SaifRehman/tendermint-chat-app/blob/master/blockchain/Dockerfile

**Comment by SaifRehman** [comment]
fixed
